name: secure_bridges_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.6+1
  http: ^0.12.0+4
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  flutter_easyloading: ^3.0.3
  cached_network_image: any
  webview_flutter: any
  flutter_webview_plugin: ^0.4.0
  image_picker: any
  intl: ^0.17.0
  google_sign_in: any
  flutter_signin_button: ^2.0.0
  flash: ^2.0.3
  charts_flutter: any
  flutter_observer: ^2.0.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^6.0.0
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
    - images/trash.png
    - images/ic_preview.png
    - images/ic_edit.png
    - images/place_holder.jpeg
    - images/ic_background.png
    - images/ic_calender.png
    - images/ic_location.png
    - images/ic_reward.png
    - images/ic_love.png
    - images/ic_addition.png
    - images/logo.jpg
    - images/ic_avatar.png
    - images/ic_edit_white.png
    - images/ic_right_arrow.png
    - images/ic_profile.png
    - images/ic_opportunity.png
    - images/ic_home.png
    - images/ic_heart.png
    - images/ic_settings.png
    - images/ic_community.png
    - images/im_padlock.png
    - images/im_helping_hand.png
    - images/im_image_background.png
    - images/ic_email.png
    - images/ic_lock.png
    - images/ic_google.png
    - images/ic_apple.png
    - images/ic_facebook.png
    - images/ic_text_show.png
    - images/im_add_user.png
    - images/ic_user.png
    - images/ic_addition_white.png
    - images/ic_heart_white.png
    - images/ic_copy.png
    - images/ic_right_arrow_white.png
    - images/ic_home_white.png
    - images/ic_multiple_users.png
    - images/ic_aid.png
    - images/ic_pizza.png
    - images/ic_notification_inactive.png
    - images/ic_notification_active.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
